### ISSUE TITLE
Make static config a docker secret

### ISSUE THREAD

**Issue by Beanow** [ArwynFr/stack-reverse#3]
https://github.com/ArwynFr/stack-reverse/blob/b6d1916b823f64b4299e5769e7f28282211ac1a7/.github/workflows/continuous-deployment.yml#L30

The workaround you shared, injects a secret into your static config.

However you're deploying this config (including secret) as a docker config.
https://github.com/ArwynFr/stack-reverse/blob/b6d1916b823f64b4299e5769e7f28282211ac1a7/stack/docker-compose.yml#L3-L7

Those are unprotected, so you should be using docker secrets for this config file instead.

**Comment by ArwynFr** [comment]
The security threat is low, as it requires access to the docker swarm, but I'll fix that eventually.
Thanks !
